

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: inotebook
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_POST: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql

  springBoot:
    build: .
    image: manishnilkanth/springboot_inotebook:0.0.1
    container_name: inotebook_application
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: inotebook
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000
    ports:
      - "8090:8080"
    depends_on:
      - mysql
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
